language: cpp

compiler:
  - gcc
  - clang

sudo: required
dist: trusty

matrix:
  allow_failures:
    - compiler: clang

install:
  - sudo apt-get install cmake g++ git freeglut3 freeglut3-dev libglpk-dev python-dev python-opengl libxmu-dev libxi-dev libqt4-dev libqt4-opengl-dev libassimp-dev libgtest-dev
  - sudo apt-get install liblog4cxx-dev

before_script:
  - echo $LD_LIBRARY_PATH
  - sudo ldconfig
  # Prepare build
  #- cd Klampt

script:
  - cd Library && make unpack-deps
  - cd KrisLibrary && git checkout logging_devel && cd ..;
  - make deps && cd ..
  - cmake .
  - make Klampt
  - cmake . -DKLAMPT_COMPILE_TESTS:BOOL=True
  - make
  - sudo make python-install
  - env CTEST_OUTPUT_ON_FAILURE=1 make test


# safelist
branches:
  only:
  - master
  - logging_devel
  - v0.7
  - travis

notifications:
  email:
    - kris.hauser@duke.edu
    - rocchi.alessio@gmail.com
